#!/bin/bash
###############################################################################
#            KM-MOD Image Classifier for Security Cameras 
#                      Sensor Analytics Australia™ 2024
###############################################################################

PyPath=/home/saauser/.venv/bin
NumC=10
PERC=80
FR=10
PROG=/mnt/SSD/dev/km-mod
MOVPATH=/mnt/SSD/MOVIE
DV=R4

if [ ! -d $PROG ] || [ ! -d $MOVPATH ]
then
   echo "dir path/s do not exist!"
   exit 1
fi

echo "program ran at $(date '+%Y-%m-%d %H:%M:%S')" 

cd $PROG

arg=12
DT_ST=$(date +%Y%m%d%H%M%S -d "$arg hours ago")
DT_EN=$(date +%Y%m%d%H%M%S)

FD=$(date +%a-%H)

$PyPath/python ./train-km-mp.py 1 $NumC $DT_ST $DT_EN
$PyPath/python ./predict-km.py $PERC

./moviefrm-list-ni $FR

mv $MOVPATH/ffnames.mp4 $MOVPATH/ffnames$DV-$FD.mp4
echo "$MOVPATH/ffnames$DV-$FD.mp4 saved"
